#  1. Create a 3x3x3 array with random values

In [8]:
import numpy as np
np.random.random((3,3,3))

array([[[0.35373242, 0.32000829, 0.7400917 ],
        [0.40110487, 0.86403555, 0.76586323],
        [0.87486686, 0.47798761, 0.27343706]],

       [[0.07508883, 0.09808741, 0.73162622],
        [0.45750228, 0.90257829, 0.02414654],
        [0.7919687 , 0.43695891, 0.46631253]],

       [[0.98253241, 0.27715367, 0.95334717],
        [0.6504318 , 0.46889336, 0.11393876],
        [0.92193356, 0.90561077, 0.04152203]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [9]:
np.diag(1+np.arange(4),-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [11]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix 

In [12]:
ar = np.random.random((5,5))
armax, armin = ar.max(), ar.min()
ar = (ar - armin)/(armax - armin)
print(ar)

[[0.77476917 0.64801102 0.67513068 0.65599415 0.27014644]
 [0.72861283 0.48902128 0.47567653 0.08946961 0.94019065]
 [0.45900471 1.         0.30550957 0.45314386 0.62021714]
 [0.         0.4611989  0.88109112 0.80613851 0.48040827]
 [0.75304087 0.36827817 0.48640636 0.84078691 0.35478665]]


# 5.  How to find common values between two arrays?

In [18]:
ar1 = np.random.randint(0,15,15)
ar2 = np.random.randint(0,15,15)
print(np.intersect1d(ar1,ar2))

[ 0  1  3  7  8  9 11 13]


# 6.How to get the dates of yesterday, today and tomorrow?

In [19]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today')+np.timedelta64(1)
print(yesterday,today,tomorrow)

2020-07-27 2020-07-28 2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [20]:
ar1 = np.random.randint(0,15,15)
ar2 = np.random.randint(0,15,15)
equal = np.allclose(ar1,ar2)
equal

False

# 8.Create random vector of size 10 and replace the maximum value by 0

In [21]:
ve = np.random.random((10))
ve[ve.argmax()] = 0
ve

array([0.0425391 , 0.8753934 , 0.        , 0.2207691 , 0.66062245,
       0.08692533, 0.82421475, 0.98207361, 0.24210592, 0.18034317])

# 9. How to print all the values of an array?

In [22]:
np.random.random((5,5))

array([[0.80717279, 0.74372533, 0.50396994, 0.99959861, 0.66085004],
       [0.96923056, 0.39474575, 0.26060801, 0.1268484 , 0.16834813],
       [0.56517465, 0.79898134, 0.10860542, 0.02536908, 0.09121026],
       [0.34997782, 0.81144373, 0.82852772, 0.38288382, 0.16574419],
       [0.88055879, 0.51099404, 0.24838321, 0.73474053, 0.62742916]])

# 10.Subtract the mean of each row of a matrix

In [23]:
ar = np.random.random((5,5))
y = ar-ar.mean()
print(y)

[[ 0.33676015  0.23078105  0.04754042  0.31930686 -0.09991305]
 [ 0.17729126 -0.01657771 -0.35123958  0.29366459  0.07887861]
 [-0.30934349 -0.22426711 -0.42091478 -0.5643104   0.33475329]
 [-0.22965244  0.02544021 -0.33583779  0.14430497  0.29761094]
 [ 0.03322151 -0.02649244 -0.20815989  0.3170655   0.15008929]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [24]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
print(Z)
print(I)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 1 7 7 8 1 6 8 3 6 0 5 7 3 7 5 1 6 9]


In [25]:
np.add.at(Z, I, 1)
print(Z)

[2. 4. 1. 3. 1. 5. 4. 5. 3. 2.]


# 12.How to get the diagonal of a dot product?"

In [26]:
A = np.random.random((5,5))
B = np.random.random((5,5))
np.diag(np.dot(A, B))

array([1.54739897, 0.82111047, 0.3166128 , 1.30450041, 1.85944071])

# 13.How to find the most frequent value in an array?

In [29]:
z = np.random.randint(0,50,15)
print(np.bincount(z).argmax())

1


# 14.How to get the n largest values of an array"

In [28]:
Z = np.arange(10000)
n = 10
print (Z[np.argsort(Z)[-n:]])

[9990 9991 9992 9993 9994 9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [27]:
Z = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
print(Z)
R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(R)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]
[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
